### PR TITLE
Add "FinalLocalVariable" and "FinalParameters" modules

### LINKED ISSUE #5: Add 'final' modules
The "FinalLocalVariable" and "FinalParameters" modules should be added to the [TreeWalker](https://github.com/duraspace/codestyle/blob/master/duraspace-checkstyle.xml#L41) module.
See: https://github.com/fcrepo4/fcrepo-build-tools/blob/master/src/main/resources/fcrepo-checkstyle/checkstyle.xml#L86-L87

Note, for ease of testing this change, https://github.com/duraspace/codestyle/issues/4 should be completed first.

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/duraspace/codestyle/pull/5

Depends on: https://github.com/duraspace/codestyle/pull/6

### CODE REVIEW

**Review by bbranan — CHANGES_REQUESTED** [review]
Please add the two Final modules to the checkstyle-suppressions.xml file as well, so that these modules  do not result in build failure for those project using the default suppressions file,

**Comment by awoods** [comment]
@bbranan : I was under the impression that each project would have its own suppressions file.

**Comment by awoods** [comment]
It sounds like we need a conversation around the expected use in each of our projects with respect to the suppression file.
I have been under the impression that the DuraSpace codestyle would be the standard to which we strive to conform, and any deviation from that standard would be reflected in the project suppression file.

**Comment by bbranan** [comment]
I'm happy to have a conversation @awoods. My original assumption with the checkstyle file was more in line with your sentiment, that it would define what we consider to be best practices. However, considering that overrides are only possible in order to suppress checks, and not add them, it's not surprising that this results in including modules that may not be a best practice across the board, but are preferred by one project, with the assumption that all other projects will suppress them. In light of that, perhaps the combination of the checkstyle and suppressions files should be considered the best practice, or at least a somewhat happy medium that is a good starting point for most projects.

**Comment by awoods** [comment]
@bbranan : From that perspective, I agree that the `final` checkstyle practice may not be fully recommended.
I am happy to add the `final` suppressions unless we collectively feel like that should be left to individual projects.

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me.  It's as discussed in today's meeting

**Review by bbranan — APPROVED** [review]

**Pull request merged**
